flags: {}
packages:
- .
- location:
    git: https://github.com/erikd/http-proxy.git
    commit: 3f7a4013c126215e61eeb34a2372b4bd1ef77c76
extra-deps:
- functor-infix-0.0.3
- taggy-0.2.0
- taggy-lens-0.1.2
resolver: lts-3.12
